version: '3.9'
services:
  backend:
    build: .
    image: dascr/backend:v1
    volumes:
      - ./data:/database
    ports:
      - "8000:8000"
    environment:
      - API_IP=0.0.0.0
      - API_PORT=8000
    networks:
      - dascr
  frontend:
    depends_on:
      - backend
    build: ./frontend/
    image: dascr/frontend:v1
    ports:
      - "8080:8080"
    environment:
      - VITE_API_BASE=http://localhost:8000/
      - VITE_API_URL=http://localhost:8000/api
      - VITE_WS_URL=ws://localhost:8000/ws
    networks:
      - dascr

networks:
  dascr:
    name: dascr
